
name: aviator_insights_pro
description: Full production scaffold
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_messaging:
  google_sign_in:
  shared_preferences:
  fl_chart:
  flutter_local_notifications:
  timezone:
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
